### ISSUE TITLE
how to use Tweens.js to make a object move follow a direction with animation and break/stop when collision a wall or barrier ?

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [enable3d/enable3d#70]
in the [document](https://enable3d.io/docs.html#tweens) , it tell me i can use `tweens` to make object move with animation .

when i took the document of `tweens` , seems like it only set the postion or rotate of three object step-by-step in the `requestAnimationFrame` . 

but how it work combine with collision ?

---

i writing a 3d simulator game , it have a small airplane and some barrier , like a ring or a wall. user must control the airplane pass through the ring OR bypass the wall with some command serials that user write before start . ( _it sounds like a small program game. IT IS ._ )

the command will like `move forward 20cm` or `move left 10cm` or `move down 50cm` or `rotate left 90digree`.

and the game will run the command serials to let the airplane bypass all the barrier and reach the checkpoint . 

i think that, **case 1** i need break move command when the airplane collision with a barrier , or **case 2** if it only rubbing the wall, i must let it follow the wall to move.

i known in the **case 1** , i can use a listener to impl it, but in **case 2**, how can i impl that ? 

if use the force and inertia to impl move instead use tweens and postion, how to control the airplane can stop in a planned distance ?

**Comment by yandeu** [comment]
I just published a [tween.js example](https://enable3d.io/examples/use-tweenjs.html).

I guess in your case it is better to use force instead of tweens. You could [disable the gravity for the plane](https://enable3d.io/examples/per-body-gravity.html) and use force to move and stop. In [this example](https://enable3d.io/examples/dash-and-blast-prototype.html), I use force to move an object in a certain direction.

Hope this helps :smiley:

**Comment by Lyoko-Jeremie** [comment]
thanks for your example ~

but i  still have a question, if i want use tweens, it dont have any way to combine with collision ?

**Comment by yandeu** [comment]
If you use tweens, you have to use a kinematic body.
Kinematic bodies do only collide with dynamic bodies.

A good option for your airplane would probably be to use the `btKinematicCharacterController`, which collides with dynamic and static bodies. I can implement the `btKinematicCharacterController` if you want.

Also read this topic:
https://discourse.threejs.org/t/ammo-js-with-three-js/12530

**Comment by Lyoko-Jeremie** [comment]
sorry for that, i dont understand how the `btKinematicCharacterController`  work , and what feature it can do.

---

BTW, not only the airplane, but also the car, i need impl the distance move with collision in project.

in now, i need impl airplane distance move with collision , and in feature, i need impl car with distance move and it need follow the topography, example, uphill, downhill , or other like ladder .

do you have something idea about this ?

**Comment by yandeu** [comment]
I will release a btKinematicCharacterController example soon.

**Comment by Lyoko-Jeremie** [comment]
>  will release a btKinematicCharacterController example soon.
thank you ~~~~~
